### ISSUE TITLE
Cannot handle web url's that are git symlinks

### ISSUE THREAD

**Issue by stonier** [vcstools/vcstools#118]
If the rosinstall file to be used by wstool is a web url representing a symlink to a relative .rosinstall file in a github repo, then this bombs. e.g.

```
wstool init testies https://raw.github.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/testies.rosinstall
```

where the contents of testies.rosinstall is:

```
../benevolent/messages-myversion.rosinstall
```

Maybe relevant:

* `wget` cannot follow the 'symlink'.
* `curl -O` can follow the symlink and download appropriately.

The git symlink isn't a real symlink, but wstool should be able to put something together to follow at least this kind of relative symlinking like curl does.

The guts of this seems to be in `vcstools.common.urlopen_netrc`.

**Comment by tkruse** [comment]
Hm, do you have a public URL I could use to reproduce? Or a way to create such a file on github?

I would like to know the exact behavior of github with respect to http return values, unless this is really just a file with the relative path as content.

**Comment by tkruse** [comment]
Just in case: The given URL `https://raw.githubusercontent.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/testies.rosinstall` does not work, not even with `curl -O`, curl just writes "404 not found" to the testies.rosinstall file for me.

**Comment by tkruse** [comment]
Whereas when I create a symlink in Linux via `ln -s` and push it, then this appears at github as you say as a file with a relative path, but neither curl nor wget download the target file.

Also as far as I can see, github provides no obvious http header to indicate that this is not a file, but a symlink.

**Comment by tkruse** [comment]
something else I notice, is that github now uses

     raw.githubusercontent.com

instead of the one you used

     raw.github.com

Attempts to download from the latter results in `HTTP 301: Moved permanently`, which redirects to the new url (raw.githubusercontent.com...). `wget` follows that by default, but `curl -O` doesn't.

**Comment by tkruse** [comment]
I created a test repo at https://github.com/tkruse/symlink_test/tree/master/foo

Even the github REST API does not yield symlink information:

    GET https://api.github.com/repos/tkruse/symlink_test/contents/foo/README2.md

```
{
  "name": "README2.md",
  "path": "foo/README2.md",
   ...
  "type": "file",
  ...
}
```

Which in itself might be worth a feature request to github. 

However, I don't see this as a bug in rosinstall. Possibly a feature request, if the need is great enough, and we can distinguish "normal" rosintall files from "github symlink" ones by inspecting the content.

**Comment by stonier** [comment]
From what I gather, the curl -O didn't work for you?

I just recreated that testies symlink, for the record the process was:

```
ln -s hello.rosinstall testies.rosinstall
git add testies.rosinstall
git commit -a -m "[rosinstall] testies again"
git push
```

and this works with 

```
curl -O https://raw.githubusercontent.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/testies.rosinstall
```

The github interface is expressing it as a symbolic link (see [here](https://github.com/yujinrobot/yujin_tools/blob/master/rosinstalls/indigo/testies.rosinstall) but for all intensive purposes, it is as you say I think, just a file with the relative reference on a single line. I know the git/github behaviour for windows/linux differs when it comes to downloading this file (windows just drops a substituted file, linux an actual symlink). Curl also seems to know what to do with this kind of file, so perhaps there is some sort of convention there.

Can we actually use curl for downloading a rosinstall file from url so that vcstools doesn't have to do anything funky itself?

**Comment by tkruse** [comment]
I get this:

    $ curl -O https://raw.githubusercontent.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/testies.rosinstall
    $ cat testies.rosinstall 
    hello.rosinstall

which is *not*

    $ curl -O https://raw.githubusercontent.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/testies.rosinstall
    $ cat testies.rosinstall
    [
      {'git': {'local-name': 'hello', 'version': 'master', 'uri':'https://github.com/stonier/hello.git'}},
    ]

the actual contents of `hello.rosinstall`. Do you get the YAML when you read testies.rosinstall after curl?

Or what else do you mean when you say "this works with curl"?

**Comment by stonier** [comment]
It looks like I've had a major brain malfunction here somewhere. Thought I'd reproduced the result for curl both at work and home, but now I'm finally not getting anywhere at all. Curl isn't even something I'd ordinarily use, but a result of some googling.

It looks like this is a dead end. Especially since as you show, the REST call doesn't provide any differentiation. The content in the downloaded file itself is not enough to positively confirm that it's a symlink in all cases. Next step, github.

Very sorry for the overhead (time) you put into this, but thanks for clearing it.

**Comment by tkruse** [comment]
No worries, it was interesting to investigate the GitHub API
