### ISSUE TITLE
Archive of version 0.1.39 is not available at http://download.ros.org/downloads/vcstools and on github

### ISSUE THREAD

**Issue by bulwahn** [vcstools/vcstools#121]
The PyPI page [1] points to http://download.ros.org/downloads/vcstools/ for downloading the vcstools python package, but unfortunately, the archive of the latest version 0.1.39 is not available there, nor is the version 0.1.39 tagged in this github repository to make the archive available here on github. Maybe these steps were forgotten or broke in the release process of this package?

[1] https://pypi.python.org/pypi/vcstools/0.1.39

**Comment by tfoote** [comment]
I've added it to download.ros.org though that's mostly for reference. PYPI now requires that it be hosted on pypi.python.org It's available here: https://pypi.python.org/packages/ab/02/4ec8ab21f821866b6a0572af37e611929594fda588b54633607cc0a25cb4/vcstools-0.1.39.tar.gz#md5=c20e19e5a5b83520329bd2040bccb375

And I've added the tag too.
