### ISSUE TITLE
python3-setuptools is a dependency

### ISSUE THREAD

**Issue by russkel** [vcstools/vcstools#131]
When using on a fresh debian (or armbian in my case) install I get an error:
```
Traceback (most recent call last):
  File "/usr/bin/vcs", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```
This is resolved by `apt-get install python3-setuptools`. Perhaps this should be added to the dependencies of the python3-vcstools package?

**Comment by wjwwood** [comment]
I think you're (understandably) confusing this repository with https://github.com/dirk-thomas/vcstool, which is where the command line `vcs` comes from, most likely. But without know what you installed it's hard to say for sure.

**Comment by russkel** [comment]
You're correct. Oops, sorry.
