### ISSUE TITLE
Add parsed url method

### ISSUE THREAD

**Issue by jayvdb** [vcstools/vcstools#133]
Currently the base `url_matches` logic is very basic, and possibly should remain very basic.

However all of the VCS implementations except bzr only use the default very basic logic.
c.f. https://github.com/vcstools/wstool/issues/112

An important part of determining similarity is parsing the url, and that can be exposed as part of the API, allowing for other types of usage in addition to 'url_matches' which is never going to have the correct equivalence logic for all users.

https://github.com/retr0h/git-url-parse is a reasonably good library for parsing git urls, with two issues raised.

I havent found a good python library for parsing hg / mercurial urls, but hg is written in python, as a usable library, so no doubt inside hg is an parser.

Likewise bzr should have a url parser in its python library.

https://github.com/sourcegraph/go-vcsurl/blob/master/vcsurl.go has an algorithm for git, hg and bzr with extra logic to enhance support for a few common hosters.

Some various URL sanitising happening at https://github.com/vcs-python/libvcs, e.g. https://github.com/vcs-python/libvcs/blob/master/libvcs/git.py#L336

A practical use for the ros community would be wstool could detect if repo hoster is offline, and skip all updates from that hoster.

**Comment by tkruse** [comment]
Is this then the same as vcstools/wstool#112, or else what is the difference?

**Comment by jayvdb** [comment]
This issue is about adding an unbiased API exposing the parts of the url in a more usable manner.

That will help building better similarity matching, but would not be the only use-case.

Hopefully there are no objections to the idea, and there is some fruitful discussion about design/implementation of this feature.

**Comment by wjwwood** [comment]
So is the idea to first parse the URL and then interpret whether or not it applies separately? (effectively splitting `url_matches()` into two parts?)

Then separately we could consider using a library to parse the url into parts? Does `urllib2` not do this for you? What advantage does `git-url-parse` give over using `urllib2` and some assertions about the scheme and path and what not?

Not saying it's not worth it, but as @tkruse expressed, I would like to understand the value added before deciding to take on a new dependency. One constraint to consider is that we build debian packages for this tool and therefore any dependencies also need to exist as debian packages or we need to package them ourselves.

Similarly, it would be fine to depend on the python libraries of mercurial and bzr so long as it's gracefully degrading, e.g. vcstools should continue to work without them installed (if I only use it with git for instance). Our debian package depends on each of those, but when installing from pip on other machines it would be best to not require them.

Another case to consider is that vcstools can be installed as python2 or python3, so if you used the python api of the bzr and hg tools then you'd need to make sure they were using the same python major version.

**Comment by jayvdb** [comment]
The additional dependencies concern is quite reasonable.
It would be easy to re-implement the algorithm instead of adding dependencies.

I think the first step would be seeing what bzr and hg python libraries provide in the way of url parsers.  I expect that if bzr and hg python libraries are not available, then the user wont be able to use bzr and hg, so parsing the urls isnt much use any way.

python2 v python3 is a much more difficult concern, as I recall (and I may be wrong or outdated about this) that both bzr and hg are py2 only, and the transition to py3 might result in py2 being dropped.

**Comment by khanchi97** [comment]
>python2 v python3 is a much more difficult concern, as I recall (and I may be wrong or outdated about this) that both bzr and hg are py2 only, and the transition to py3 might result in py2 being dropped.

yes, it could be more difficult if you used the python api of hg as @wjwwood said "then you have make sure that they were using the same python version."
>I think the first step would be seeing what bzr and hg python libraries provide in the way of url parsers.

Here, I think @Pulkit07 can give valuable suggestion on this :)

**Comment by Pulkit07** [comment]
> python2 v python3 is a much more difficult concern, as I recall (and I may be wrong or outdated about this) that both bzr and hg are py2 only, and the transition to py3 might result in py2 being dropped.

Currently, we are working to make Mercurial compatible across both Python 2 and 3. So definitely we will have a hg version which support both versions of Python.

(Thanks @khanchi97 for the mention)

**Comment by jayvdb** [comment]
Thx @Pulkit07. Do you know where the hg remote url parser is? Is it part of the stable external API which other apps can rely on?

**Comment by tkruse** [comment]
Actually, even if we technically could depend on Mercurial as a library, for our purposes it might be cheaper and safer to copy and include the sources of such a URL parser if available in python (if the license allows it).

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
