### ISSUE TITLE
Release 0.1.41 (or newer)

### ISSUE THREAD

**Issue by 130s** [vcstools/vcstools#146]
Last release, if I'm not mistaken, was [an year ago](https://github.com/vcstools/vcstools/releases/tag/0.1.40). Looks like several committs have been made including some important update for newer platforms.

Some of the checklist (feel free to edit):
- [x] https://github.com/vcstools/vcstools/pull/141 Python3
- [x] https://github.com/vcstools/wstool/issues/77  (attempt to fix that is open on this repo https://github.com/vcstools/vcstools/pull/144) Frequent, longstanding bug upon `wstool update`.

**Comment by 130s** [comment]
The items in OP, which I contributed to compile so there can be more to be added, are checked. Since some of them are critical in some usecases as mentioned in each ticket, I think new release makes sense. Could @clalancette @tfoote or anyone take care of this soon?

**Comment by 130s** [comment]
Friendly ping  @clalancette @tfoote

**Comment by 130s** [comment]
Is there any blocker for this?

**Comment by tkruse** [comment]
It needs somebody with time for this to be handed over release privileges. That's all.

**Comment by rotu** [comment]
Agreed. The change to remove reliance on Bash features in git_archive_all.py is big for me.

**Comment by tkruse** [comment]
I made test-release to https://test.pypi.org/project/vcstools/

This contains all fixes except the windows compatibility (https://github.com/vcstools/vcstools/pull/139). I would need more time to review and bless it.

@wjwwood do you want to have a final look at the last commits I merged or the testpypi files? Else I am good to make the release (or you could do). Next would be wstool and rosinstall, which are also prepared.

**Comment by wjwwood** [comment]
I created an account: https://test.pypi.org/user/wwoodall/

**Comment by wjwwood** [comment]
Changes look fine to me. I'll do a release (since our tool does pypi and deb at the same time).

**Comment by wjwwood** [comment]
I had to remove `cosmic` and `disco` for now from the `stdeb.cfg` since we don't have hosting for those yet, so I made a `0.1.42` in the meantime. But of course trying to use them broken something so I'm waiting on feedback from others on how to fix it 🤦‍♂. I'll try to finish up the release shortly afterwards.

**Comment by wjwwood** [comment]
Ok, `0.1.42` can be installed from pip and apt (if you have either the ROS 1 or ROS 2 deb repo added).
