### ISSUE TITLE
python-vcstools 0.1.42-1 breaks Hydro (on Ubuntu Precise)

### ISSUE THREAD

**Issue by mintar** [vcstools/vcstools#157]
The tests for opencv_apps started failing recently.

3 months ago, the test still worked (with python-vcstools 0.1.40-1): https://travis-ci.org/ros-perception/opencv_apps/jobs/568615356#L645

Now it breaks (with python-vcstools 0.1.42-1): https://travis-ci.org/ros-perception/opencv_apps/jobs/602348692#L650

So somebody uploaded a new version to the ROS package repository for Precise within the past 3 months. This new version contains a control.tar.xz file, which the old version of dpkg on Precise doesn't understand. Could you please release a version into Precise that doesn't have the control.tar.xz file?

If I correctly understand @dirk-thomas 's comment on the [Discourse thread](https://discourse.ros.org/t/python-vcstools-0-1-42-1-breaks-hydro-on-ubuntu-precise/11188), this means that the PC where `bloom-release` is executed must have an old Ubuntu version that doesn't produce control.tar.xz files yet.

**Comment by wjwwood** [comment]
I don't know how to fix this, if someone gives my instructions I can try it.

Generally though, why are you testing Hydro... Like seriously it's been EoL for four years.

**Comment by tfoote** [comment]
Note that this doesn't got through the `bloom-release` pipeline but the ros_release_python https://github.com/ros-infrastructure/ros_release_python but yes it needs the older version of `debhelper`, which generates the packages, for the building process if it's being released back that far so that the older version of dpkg can read the package.

Other references: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627 and https://github.com/ros/rosdistro/issues/19481

**Comment by mintar** [comment]
> I don't know how to fix this, if someone gives my instructions I can try it.
> 
> Generally though, why are you testing Hydro... Like seriously it's been EoL for four years.

I agree that this test should be removed (BTW, I'm not a maintainer of opencv_apps, just an innocent bystander).

The concern for me is not making this test in opencv_apps pass, but getting the Hydro package archive back to a usable state. I can't give you instructions on how to do this using `ros_release_python`, but maybe you can just restore the repository from a backup (before the release of python-vcstools 0.1.42-1)? If possible, it would also be good to make the Hydro repo read-only, so this doesn't happen again in the future.

**Comment by tfoote** [comment]
There are read only snapshots in our snapshots repository: http://wiki.ros.org/SnapshotRepository

I'd recommend using that for your purposes. We could actually consider turning off older platforms on our main repository too. @nuclearsandwich FYI

**Comment by nuclearsandwich** [comment]
> We could actually consider turning off older platforms on our main repository too. @nuclearsandwich FYI

This is something I'd enjoy doing just to cut down on space usage and transfer times when importing from the bootstrap repo. However I'd want to revisit our snapshot repo costs and the traffic for older distros before we require folks to migrate.

An intermediate solution is to stop publishing updated tools to EOL distros. We do this most of the time just by pruning the release suites but we could enforce it by removing those distros from the auto-publish script after package import.

**Comment by nuclearsandwich** [comment]
My proposal would be to merge #154 and restore a previously working version in Precise. I can do so manually with the bootstrap repo and then propagate that out.

**Comment by wjwwood** [comment]
> I can do so manually with the bootstrap repo and then propagate that out.

Thanks, I think that makes sense. I tried to build a deb for the new version in a Precise docker instance, but didn't have much luck. Restoring the old version on Precise seems like a good idea to me.

**Comment by nuclearsandwich** [comment]
For reasons unknown, python-vcstools 0.41.1 is missing a binary deb in the bootstrap archives. But python-vcstools 0.40.1 is present and could be rolled back to in Precise quite easily.

**Comment by mintar** [comment]
> For reasons unknown, python-vcstools 0.41.1 is missing a binary deb in the bootstrap archives. But python-vcstools 0.40.1 is present and could be rolled back to in Precise quite easily.

+100 for restoring python-vcstools 0.40.1 . As I wrote in my original post here, that's the last known working version that I've seen.

**Comment by nuclearsandwich** [comment]
Over the weekend I reverted the vcstools packages in precise to 0.40.0. @mintar does that resolve the issue for you?

**Comment by mintar** [comment]
Yes, I've verified that python-vcstools was rolled back to 0.1.40-1 and that the opencv_apps tests now work again on precise, so I'm closing this ticket. Many thanks for resolving the issue!
