### ISSUE TITLE
push command

### ISSUE THREAD

**Issue by tkruse** [vcstools/vcstools#24]
For discussion, regarding
https://github.com/vcstools/rosinstall/issues/5

In my opinion this is feasible, but the abstracted behavior should be that of a linear centralized workflow (like svn) even for the distributed case. So what I suggest is that for the distributed SCMs we first check whether we are locally at the tip of the tracked remote branch, and only do [add, commit, push] if so.
Also to reduce risk of abuse, I would suggest the API requires to tell which files to commit.

My initial shot an an API would therefore be SVN inspired:
commit(files, message) requiring both arguments to be filled, which should grant that under normal circumstances, all changes in all files are collected in a single commit that exists both locally and remote (if a remote is known).

Else, I wonder whether some release code may not require an ability to create branches and tags. Offering more such options through rosws could help get a standard SCM layout accross many ROS packages, such as having groovy-devel / hydro-devel branches and consistent tag names.

For that, we could have APIs like
create_tag(tagname, local_only=False)
and
maybe update(..., auto_create_branch=True)

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
