### ISSUE TITLE
svn export_repository function version quirk

### ISSUE THREAD

**Issue by tkruse** [vcstools/vcstools#26]
Hi,

this goes mostly to William, I guess, but we may all need to discuss.

I notice the code in svn.py for export_repository reads:

```
cmd = 'svn export {0} {1}'.format(os.path.join(self._path, version),
                                      basepath)
```

This would only make sense if one had checked out the repository root and then passed
'trunk' or 'branches/foo' as version. This however is inconsistent with the rest of vcstools,in particular this does not allow to pass a simple revision number to export that revision.

I also notice the same logic seems to be underlying the original get_branches() pull request.

I would suggest changing export_repository to fall in with the intended rosinstall usage of vcstools, and discuss the need of export_repository/ get_branches that led to this implementation.

At the very least, the export_repository needs to overly clear explain that it will use the version argument as a subfolder path and that this only makes sense for checked out repository roots.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
