### ISSUE TITLE
less stateful behavior of rosws / rosinstall

### ISSUE THREAD

**Issue by tkruse** [vcstools/vcstools#27]
Following comments by @wjwwood in our forum, I suggest the following change to rosinstall / rosws behavior.

Background: The rosinstall syntax defines configuration elements where each may have a localpath, url, and version. This allows to define rosinstall files for projects so that each team member can install from this rosinstall file and be on the intended branch/tag for his project (e.g. ros-fuerte.rosinstall vs. ros-groovy.rosinstall).
This tripel is stored locally in the .rosinstall file on checkout of these elements. Based on the current simple rosinstall semantics, the local .rosinstall files defines the state that the workspace should be in until further changes to the .rosinstall. This means every "rosws update" action will attempt to recretae the state given in the .rosinstall. A beneficial aspect is that one may delete a folder, call rosws update, and get it back from its origin.

Another beneficial aspect is that one may merge with a different rosinstall file, get new versions, and then intentionally switch to the new versions in all local repositories.

A negative aspect is that if the user manually changed the state of a local repository to something else (e.g. switch a branch), rosws update would change back to the stored state.

I suggest that we change the default behavior of rosws update and rosinstall to disregard the stored version in the .rosinstall if there is a local checkout already. The semantics will then fall back on whatever update reasonably means to the vcs.

This may be complemented by some non-default option to restore the state in the .rosinstall file.

This would e.g. break the following use case:
rosws init .
rosws merge groovy-stable.rosinstall
rosws update
rosws merge groovy-unstable.rosinstall # this only changes version values in .rosinstall
rosws update # before, this would update to the new version, now it does nothing

rosws update --from-spec  # this could be the fallback option to get the legacy behavior

I believe that there is no heavy infrastructure currently that relies on this use-case (but I may be wrong).

I am happy to create a REP for that if we agree that this change would be beneficial.
So the question is whether I we can break the use-case I have given, and whether there is another important use-case that would break.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
