### ISSUE TITLE
git pull variant

### ISSUE THREAD

**Issue by tkruse** [vcstools/vcstools#30]
It has been suggested to add an option to vcstools to call through to 'git pull'.

One alternative is an update_merge() vcstools API command, where in the case of divergence, git would attempt to create a merge commit. 
Something similar could be implemented for mercurial, which currently updates like this:
"hg update %s --config ui.merge=internal:fail"
but could be made to conflict-merge instead, using something like "hg pull -u"

Making merge on option of update() is a bit dirty since update also serves to switch branches and checkout earlier tags, and the semantics of a merge option would be difficult then. One could raise ValueError if both a different spec and the merge option have been provided, unless we also wanted to provide an abstract API for creating merges.

This command/option would obviously not be used by rosws or any other tool intended to be safe, but a vcstool implementation could benefit from that.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
