### ISSUE TITLE
vcs branches and tags

### ISSUE THREAD

**Issue by tfoote** [vcstools/vcstools#4]
For UI purposes, it could be interesting to retrieve all known branches and tags of repositories. For SVN, this would become even more useful with ticket 3, updating for tags and branches. 
Also all SCMs seem to have at least one default concept of branches and tags, and it could be interesting to retrieve it.
e.g. get_named_references(branches = True, tags = True)

https://kforge.ros.org/vcstools/trac/ticket/4

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
