### ISSUE TITLE
svn tags and branches

### ISSUE THREAD

**Issue by tfoote** [vcstools/vcstools#5]
Working with svn branches and tags is not currently possible in vcstools. However, abstracting from the implementation details of svn, it should be possible.
The URL:
 https://code.ros.org/svn/ros/stacks/ros_comm/tags/ros_comm-1.6.2
Can be split up into
URL:  https://code.ros.org/svn/ros/stacks/ros_comm
Tag: ros_comm-1.6.2
So, if the URL contains "/trunk/" "/tags/" or "/branches/", I believe it should be possible to allow e.g. update(spec="ros_comm-1.6.3"), or update(spec="trunk") and vcstools checks whether a suitable URL exists and does "svn switch". Disambiguating can be done using sensible rules. Not svn does else only allow revision numbers or very few keywords for "svn update", and it is uncommon and bad practice to name branches or tags with integers.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
