### ISSUE TITLE
update process freezes when using the git credential helper to cache user credentials

### ISSUE THREAD

**Issue by meyerj** [vcstools/vcstools#67]
We are using password-protected git http repositories internally which we would like to be updated from rosws workspaces, too. To save the users to enter their credentials once for each repository, we recommend to use the cache credential helper (see https://www.kernel.org/pub/software/scm/git/docs/git-credential-cache.html). This method works fine if you manually pull from multiple repos within a certain time period and the password must only be entered for the first repo. Of course there are other methods to store the credentials permanently with git that do not require user interaction during fetch or push operations, but as we use a single shared user account on some machines storing the git passwords is no option for us.

Unfortunately, when using rosws to pull updates from the server, using cached credentials causes rosws to wait indefinitely after the user has entered his password for the first repo.

Before having entered the password:

```
 6568 pts/3    Ss     0:00 bash
10341 pts/3    S+     0:00  \_ /usr/bin/python /usr/bin/rosws up
10398 pts/3    Sl+    0:00      \_ /usr/bin/python /usr/bin/rosws up
10406 pts/3    S+     0:00      \_ /bin/sh -c git fetch
10407 pts/3    S+     0:00          \_ git fetch
10408 pts/3    S+     0:00              \_ git-remote-https origin https://hector.gkmm.informatik.tu-darmstadt.de/git/tu-darmstadt-ros-pkg/hector_common.git
```

After having entered the password:

```
 6568 pts/3    Ss     0:00 bash
10341 pts/3    S+     0:00  \_ /usr/bin/python /usr/bin/rosws up
10398 pts/3    Sl+    0:00      \_ /usr/bin/python /usr/bin/rosws up
10488 pts/3    Z+     0:00      \_ [sh] <defunct>
```

The fact that git asks for user credentials itself is not a problem. Without the credential helper the password must be entered twice per protected repo, which is quite annoying, but the update runs fine. If one of the repositories has been updated manually with "git pull" within the credential cache timeout, rosws also does not stop and uses the cached credentials.

This bug also affects wstool, so I guess it is related to the vcstools package. Might also be related to #12. I don't think that this issue affects many users and would give it a lower priority. Nevertheless it would be great to get this fixed if there is a simple solution or workaround.

**Comment by kartiksubbarao** [comment]
FYI, the root cause of this problem is that the git credential-cache--daemon process doesn't close stderr, so the Popen() function keeps waiting to read from it. The good news is that this has been resolved as of git 2.2.0:

https://github.com/git/git/commit/f5e3c0b9d050ebdaf96d3910b01b01695e3ea1a2
