### ISSUE TITLE
force option

### ISSUE THREAD

**Issue by tfoote** [vcstools/vcstools#7]
Common to all vcs seems the option to discard local changes using --force. This could go into the vcstools API.

Also, throwing in thses commonalities as good candidates:
annotate/blame
diff to / between revisions (currently only uncommited changes)
cat version
info / summary
log

https://kforge.ros.org/vcstools/trac/ticket/2

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
